export const ROLES = [
    "software engineer",
    "roboticist",
    "full-stack developer",
    "systems programmer",
    "data engineer",
    "computer vision engineer",
    "applied math student",
    "operations researcher",
    "designer",
    "brand designer",
    "writer",
    "journalist",
    "editor",
    "photographer",
    "hackathon winner",
    "founder",
    "team captain",
    "open-source contributor",
    "researcher",
    "web developer",
    "agent builder",
    "teacher",
    "debater",
    "tinkerer",
] as const;

export const LIKES = [
    "making slow code 1000x faster",
    "tracking things through a camera",
    "robots that drive themselves",
    "AI agents that do real work",
    "search engines",
    "sunspots",
    "predicting solar flares",
    "big, messy datasets",
    "data pipelines that don't break",
    "good typography",
    "brands with a point of view",
    "shipping on a deadline",
    "winning hackathons",
    "writing that changes minds",
    "editing other people's drafts",
    "photography",
    "whales",
    "fast websites",
    "cutting hosting bills to almost nothing",
    "open source",
    "open-source investigations",
    "timestamping audio from the power grid",
    "linear algebra",
    "abstract algebra",
    "control theory",
    "Kalman filters",
    "path planning",
    "point clouds",
    "teaching kids to code",
    "leading small teams",
    "FIRST robotics",
    "spatial computing",
    "on-device machine learning",
    "semantic search",
    "arguing well",
    "getting a school board to change its mind",
    "tools for editors",
    "admin dashboards people enjoy",
    "measuring before optimizing",
    "multithreading",
    "shaders",
    "canvas animation",
    "early-stage startups",
    "building from scratch",
    "hard problems with small teams",
    "turning notes into tools",
    "scouting data",
    "benchmarks",
    "operations research",
    "a good resume",
] as const;
